### ISSUE TITLE
python-six dependency blocking Humble release

### ISSUE THREAD

**Issue by dcconner** [FlexBE/flexbe_behavior_engine#12]
python-six dependency introduced in https://github.com/team-vigir/flexbe_behavior_engine/pull/102
Is causing issues for Humble release on RHEL.

Repeating question posted there for @pschillinger @fmessmer 

What does `six.moves.queue` have over standard `queue` module?

I'd like to go back to `queue` to avoid issue on ROS 2 release as RHEL does not have python-six.
Or is there some reason for `python-six` and I should:
* just drop RHEL?
* try to convert dependency to python3-six?

**Comment by fmessmer** [comment]
back then (Jan 2020), these changes were made with python2/python3 compatibility in mind, IIRC

 > the changes were produced by running `2to3 -wn .`

`pylint` reported issues and `2to3` suggested these changes...

I guess python2 is no longer relevant anymore...
