### ISSUE TITLE
AttributeError: module 'rclpy.signals' has no attribute 'SignalHandlerOptions'

### ISSUE THREAD

**Issue by zeidk** [FlexBE/flexbe_behavior_engine#13]
Hello, 

I am using ros2-devel branch for Galactic. The command ``ros2 launch flexbe_onboard behavior_onboard.launch.py use_sim_time:=False`` raises the error below:

```
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [start_behavior-1]: process started with pid [1000498]
[start_behavior-1] Traceback (most recent call last):
[start_behavior-1]   File "/home/zeid/ariac_eval_ws/install/flexbe_onboard/lib/flexbe_onboard/start_behavior", line 33, in <module>
[start_behavior-1]     sys.exit(load_entry_point('flexbe-onboard==2.3.2', 'console_scripts', 'start_behavior')())
[start_behavior-1]   File "/home/zeid/ariac_eval_ws/install/flexbe_onboard/lib/python3.8/site-packages/flexbe_onboard/start_behavior.py", line 43, in main
[start_behavior-1]     signal_handler_options=rclpy.signals.SignalHandlerOptions.NO)  # We will handle shutdown
[start_behavior-1] AttributeError: module 'rclpy.signals' has no attribute 'SignalHandlerOptions'
```

This is due to ``signal_handler_options`` not being recognized in the following snippet.

```
rclpy.init(args=args, signal_handler_options=rclpy.signals.SignalHandlerOptions.NO)
```

**Comment by dcconner** [comment]
The ros2-devel is currently aligned with Humble.  There are significant changes from Galactic to Humble as ROS 2 has evolved.  Those options were added to allow a more graceful shutdown with Ctrl-C.   You can remove that in your source code.  I do not anticipate back porting the recent changes to Galactic, and as the ROS 2 version  was under active development during switch to Humble there is no well defined "Galactic branch". 

My suggestion is to fork ros2-devel, then make the changes required to undo the Humble specific changes.
My experience was that Humble is the more mature version over Foxy or Galactic, which is not a Long Term Support version, so you may want  consider moving to Humble.

**Comment by zeidk** [comment]
Is there a way to create a galactic branch with the understanding that the galactic branch will not have future updates? Some projects clone the ros2-devel branch as it was working with galactic at some point.

**Comment by dcconner** [comment]
There is a decent chance that you could checkout and branch from last year's Humble release 345e65c09bbfca6a0c74b0b5e833158ae9b4ca3b and it would work for Galactic.

But there are a number of changes this year that you would probably want.  

I'm suggesting that you create your own branch off of current ROS 2, remove the `signal_handler_options=rclpy.signals.SignalHandlerOptions.NO) ` from start_behavior.py and try that.  It will likely crash on Ctrl-C, but that will not be an issue with running.  

My problem is I've moved my setup away from Galactic and don't have bandwidth to prepare and release a tested Galactic branch.  If you want to test the above change and let me know, then I can create a galactic branch that you could issue pull requests to.  It will need to wait a few days as I'm current traveling.
