### ISSUE TITLE
flexbe_mirror setup.py lists unnecessary console scripts

### ISSUE THREAD

**Issue by robwoolley** [FlexBE/flexbe_behavior_engine#15]
Hi,

I am investigating a build failure that we are seeing in building flexbe_mirror when building ROS 2 for OpenEmbedded / Yocto Project: https://github.com/ros/meta-ros/issues/1077

I used the official ROS2 container images to investigate how the flexbe_mirror and mirror_state console scripts behave normally.  When I tried to run the scripts directly it seems like the entry point may not be set properly:

```
/opt/ros/humble/lib/flexbe_mirror/flexbe_mirror
Traceback (most recent call last):
File "/opt/ros/humble/lib/flexbe_mirror/flexbe_mirror", line 33, in <module>
sys.exit(load_entry_point('flexbe-mirror==2.3.3', 'console_scripts', 'flexbe_mirror')())
TypeError: 'module' object is not callable
```

I could be mistaken, but I believe that [lines 25 and 26 of the [setup.py](https://github.com/FlexBE/flexbe_behavior_engine/blob/ros2-devel/flexbe_mirror/setup.py#L25) for flexbe_mirror and mirror_state may be unnecessary as "behavior_mirror_sm" seems to use the FlexbeMirror and MirrorState classes and the other scripts do not have a main() entry point.

Cheers,
Rob

**Comment by dcconner** [comment]
Fixed in ros2-devel.  Will cherry-pick into iron and rolling later.  @robwoolley Do you need in humble?

**Comment by robwoolley** [comment]
Yes, please.  I plan to support Humble for the next 3 years until it goes end of life.

Thank you!

**Comment by dcconner** [comment]
merged into humble branch with some additional changes.
A release tag and binary will follow soon(ish)
