### ISSUE TITLE
Delay available in behaviour_launcher_main before Setting up behavior_launcher is not enough

### ISSUE THREAD

**Issue by AravindaDP** [FlexBE/flexbe_behavior_engine#20]
Time delay loop available at https://github.com/FlexBE/flexbe_behavior_engine/blob/iron/flexbe_widget/flexbe_widget/behavior_launcher.py#L266 is not enough to give time to `_status_callback` to get called. So trying to launch behaviors with following command fails. (With `ros2 launch flexbe_onboard behavior_onboard.launch.py` already called in a seperate terminal)

`rosrun flexbe_widget be_launcher -b 'Example Behavior'`

```
[INFO] [1716011288.849518090] [flexbe_widget]: 1 behaviors available, ready for start request.
Set up behavior_launcher with 'Example Behavior' ...
Add callback request for 'Example Behavior' ...
Run initial request of behavior_launcher spinner ...
[ERROR] [1716011288.974051574] [flexbe_widget]: Behavior engine is not ready - cannot process start request!
[INFO] [1716011288.974993184] [flexbe_widget]: Initial behavior launcher request is sent!
Start behavior_launcher spinner ...
[INFO] [1716011297.819500334] [flexbe_widget]: BE status code=20 received - READY for new behavior!
```

Increasing time delay to 0.02 or more (So total delay is 2s or more for loop of 100) seems to resolve the issue. (Or best is to wait till `_ready_event.is_set()` or a max time out of 5sec.)

```
[INFO] [1716012112.849948804] [flexbe_widget]: 1 behaviors available, ready for start request.
Set up behavior_launcher with 'Example Behavior' ...
[INFO] [1716012113.442451071] [flexbe_widget]: BE status code=20 received - READY for new behavior!
Add callback request for 'Example Behavior' ...
Run initial request of behavior_launcher spinner ...
[INFO] [1716012114.903119699] [flexbe_widget]: Got message from request behavior for Example Behavior
[INFO] [1716012114.903953843] [flexbe_widget]: Processing request using behavior 'Example Behavior' from package='example_flexbe_behaviors' with key=1205735444 ...
[INFO] [1716012114.905562292] [flexbe_widget]: Check for behavior change ...
[INFO] [1716012114.906543963] [flexbe_widget]: No changes to behavior version - restart
[INFO] [1716012114.907227931] [flexbe_widget]: Initial behavior launcher request is sent!
Start behavior_launcher spinner ...
``

**Comment by dcconner** [comment]
I am planning to add a subscription to the onboard heartbeat (already subscribed by mirror).
The behavior launcher will not trigger until a heartbeat is received

**Comment by dcconner** [comment]
See 1c3718a42a791a26df67287303c6b617c16a583e in iron branch.

Will cherry-pick to humble/rolling/ros2-devel soon

**Comment by AravindaDP** [comment]
The issue is at https://github.com/FlexBE/flexbe_behavior_engine/blob/iron/flexbe_widget/flexbe_widget/behavior_launcher.py#L115 it checks for `_ready_event.is_set()` and actually it seems sometimes takes more than 2 seconds (in some occasions almost 5~10 sec) to be set.

So perhaps we should check for that condition at https://github.com/FlexBE/flexbe_behavior_engine/blob/iron/flexbe_widget/flexbe_widget/behavior_launcher.py#L284 instead?

**Comment by dcconner** [comment]
Just pushed an update 826cf3b3c6ab7b7ab19216f9757d134e311660cd that allows a "-s" or "--autostart" option that will enable the launcher to send behavior start request as soon as initial heartbeat is received if no other behavior is active.  The heartbeat is published every second, where the READY signal is only published every 10 seconds after initial change (to avoid spamming the UI).  Without the --autostart option it will wait for the ready signal.  @AravindaDP let me know what you think

**Comment by AravindaDP** [comment]
Tested and both options worked for me as per your explanation. Thanks for your time. Closing the issue now.
