### ISSUE TITLE
ROS-Galactic 

### ISSUE THREAD

**Issue by Shubhamtakbhate1998** [FlexBE/flexbe_behavior_engine#4]
Unable to connect to ROS master in galactic. What could be the reason

**Comment by dcconner** [comment]
ROS Galactic is ROS 2, so it does not have a "master" node.  If you mean your flexbe setup is not getting messages via DDS, then we will need more information about your setup to help debug.  Which OS? Which branch of flexbe?  Can you post a screen shot of your errors.  What specifically is not communicating?

**Comment by Shubhamtakbhate1998** [comment]
Hi,
I managed to solve the issue. Thank you for your response.
