### ISSUE TITLE
some ROS 2 states are still using ROS 1 actions

### ISSUE THREAD

**Issue by christian-rauch** [FlexBE/flexbe_behavior_engine#5]
The `InputState` state:
https://github.com/FlexBE/flexbe_behavior_engine/blob/de7528119d2bc564740e95a33a5b1e96dbde8f5c/flexbe_states/flexbe_states/input_state.py#L5
and `BehaviorInput`:
https://github.com/FlexBE/flexbe_behavior_engine/blob/de7528119d2bc564740e95a33a5b1e96dbde8f5c/flexbe_input/flexbe_input/flexbe_input.py#L8
are still using the ROS 1 action. This should probably be `from flexbe_msgs.action import BehaviorInput`. And other usages of `BehaviorInputAction` should be replaced with `BehaviorInput`.

**Comment by dcconner** [comment]
Thanks for reporting.  I will be putting some effort into ROS 2 over the next couple of weeks.  Happy to accept PRs

**Comment by dcconner** [comment]
should be fixed on ros2-devel and humble branches now
